---
# group_vars/all/network.yml
network_topology:
  trusted:
    iface: "{{ vault_iface_trusted | default(omit) }}"
    ip: "{{ vault_ip_br_trusted | default(omit) }}"
    network: "{{ vault_net_br_trusted | default(omit) }}"
    subnet: "{{ vault_subnet_trusted | default(omit) }}"
    gateway: "{{ vault_gw_trusted | default(omit) }}"
    dhcp_range: "{{ vault_dhcp_range_trusted | default(omit) }}"
    wifi_ssid: "{{ vault_wifi_ssid_trusted | default(omit) }}"
    mac_wifi1: "{{ vault_mac_wifi1_br_trusted | default(omit) }}"
  work:
    iface: "{{ vault_iface_work | default(omit) }}"
    ip: "{{ vault_ip_br_work | default(omit) }}"
    network: "{{ vault_net_br_work | default(omit) }}"
    subnet: "{{ vault_subnet_work | default(omit) }}"
    gateway: "{{ vault_gw_work | default(omit) }}"
    dhcp_range: "{{ vault_dhcp_range_work | default(omit) }}"
    wifi_ssid: "{{ vault_wifi_ssid_work | default(omit) }}"
    mac_wifi1: "{{ vault_mac_wifi1_br_work | default(omit) }}"
  iot:
    iface: "{{ vault_iface_iot | default(omit) }}"
    ip: "{{ vault_ip_br_iot | default(omit) }}"
    network: "{{ vault_net_br_iot | default(omit) }}"
    subnet: "{{ vault_subnet_iot | default(omit) }}"
    gateway: "{{ vault_gw_iot | default(omit) }}"
    dhcp_range: "{{ vault_dhcp_range_iot | default(omit) }}"
    wifi_ssid: "{{ vault_wifi_ssid_iot | default(omit) }}"
    mac_wifi2: "{{ vault_mac_wifi2_br_iot | default(omit) }}"
  guests:
    iface: "{{ vault_iface_guests | default(omit) }}"
    ip: "{{ vault_ip_br_guests | default(omit) }}"
    network: "{{ vault_net_br_guests | default(omit) }}"
    subnet: "{{ vault_subnet_guests | default(omit) }}"
    gateway: "{{ vault_gw_guests | default(omit) }}"
    dhcp_range: "{{ vault_dhcp_range_guests | default(omit) }}"
    wifi_ssid: "{{ vault_wifi_ssid_guests | default(omit) }}"
    mac_wifi2: "{{ vault_mac_wifi2_br_guests | default(omit) }}"
  servers:
    iface: "{{ vault_iface_servers | default(omit) }}"
    ip: "{{ vault_ip_br_servers | default(omit) }}"
    network: "{{ vault_net_br_servers | default(omit) }}"
    subnet: "{{ vault_subnet_servers | default(omit) }}"
    gateway: "{{ vault_gw_servers | default(omit) }}"
    dhcp_range: "{{ vault_dhcp_range_servers | default(omit) }}"
  media:
    iface: "{{ vault_iface_media | default(omit) }}"
    ip: "{{ vault_ip_br_media | default(omit) }}"
    network: "{{ vault_net_br_media | default(omit) }}"
    subnet: "{{ vault_subnet_media | default(omit) }}"
    gateway: "{{ vault_gw_media | default(omit) }}"
    dhcp_range: "{{ vault_dhcp_range_media | default(omit) }}"
    wifi_ssid: "{{ vault_wifi_ssid_media | default(omit) }}"
    mac_wifi1: "{{ vault_mac_wifi1_br_media | default(omit) }}"
  failsafe:
    ip: "{{ vault_ip_br_failsafe | default(omit) }}"
    network: "{{ vault_net_br_failsafe | default(omit) }}"
    subnet: "{{ vault_subnet_failsafe | default(omit) }}"
    gateway: "{{ vault_gw_failsafe | default(omit) }}"
    dhcp_range: "{{ vault_dhcp_range_failsafe | default(omit) }}"
  vpn:
    iface: "{{ vault_iface_vpn | default(omit) }}"
    server_ip: "{{ vault_wg_server_ip | default(omit) }}"
    network: "{{ vault_wg_server_network | default(omit) }}"
    subnet: "{{ vault_wg_network_cidr | default(omit) }}"
    listen_port: "{{ vault_wg_listen_port | default(omit) }}"
