repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c, .yamllint]

  - repo: local
    hooks:
      - id: ansible-lint
        name: Ansible-lint
        entry: ansible-lint
        language: system
        files: \.(yaml|yml)$

  - repo: local
    hooks:
      - id: check-ansible-vault
        name: Check Ansible Vault encryption
        entry: bash -c 'for f in "$@"; do if ! head -n 1 "$f" | grep -q "\$ANSIBLE_VAULT"; then echo "File $f is not encrypted!"; exit 1; fi; done' --
        language: system
        files: vault\.yml$
