---
all:
  children:
    rpi_server:
      hosts: rpi
    control_node:
      hosts: localhost
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
